# -*- coding: utf-8 -*-
"""multi_agent_workflow_CrewAI_self-operating_culinary_task_creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S18N9x6rjyOTuv-rPzGdHATX-qgYGn2Q
"""



"""
# Workflow Title:

Multi-Agent Workflow using CrewAI for Self-Operating Culinary Task Creation

# Overview:
•	CrewAI used for a team of agents communication is applicable for making independent AI workflows.
•	Agents can communicate tasks, synchronize knowledge, and yield reliable outputs
•	one example to support CrewAI self-operating AI pipeline included.
•	This project illustrates how AI carries a real-world multi-agent workflow in practical scenarios.

"""



"""# Underlying Technologies:

•	Python programming
•	Google Colab
•	OpenAI: gpt-4o-mini as LLM
•	CrewAI used for multi-actor workflow including task conversation under the LLM infrastructure
•	Query Engineering under LLM

# Mission:

•	Make self-managed multi-agent system and run it.
•	Communicate between agents to make personalized recipes by keeping food preference rules.
•	Make logical decisions with a simple example using CrewAI’s flow pipeline.
•	Reproducible output received.

# Notable Points:

•	Created a multi-agent workflow under CrewAI.
•	culinary_agent working as LLM agent can understand how to manage food elements, nutritional restrictions, and user preferences.
•	Organized tasks through multiple ways: recipe planning, tuning, and result presentation
•	Presented self-directed engine using agentic logic and AI query structuring.
•	AI pipelines working under NLP fields.
"""

import os

#%%capture
!pip install crewai

# using 'userdata' to read key
from google.colab import userdata

api_key = userdata.get('OPENAI_API_KEY')

os.environ['OPENAI_API_KEY'] = api_key

from crewai import LLM

#from crewai import Agent, Task, Crew, LLM

# setup an LLM with OpenAI model ('gpt-4o-mini')

llm = LLM(model = 'gpt-4o-mini')

# agent input setup

flavor_bases = ['garlic', 'chicken', 'mushroom', 'tofu']

food_allergies = ['nuts',  'red meat', 'high sodium', 'spicy foods']

from crewai import Agent

# change lists into text.
flavor_bases_list_text = ','.join(flavor_bases)
food_allergies_list_text = ','.join(food_allergies)

# Note: Do not rename the keyword arguments llm, role, backstory, goal, or verbose placed inside the Agent().

culinary_agent =  Agent(
    llm=llm,
    role = 'culinary_agent',
    backstory=(
        'You are a professional culinary AI helper with clear understanding how to build recipes through smart taste matching and nutritional knowledge.'
        'You make meals that use recipe elements with respect to all food sensitivities.'),
    goal = (
    f'Make recipes which incorporate any of the highlighted flavor components: {flavor_bases_list_text}.'
    f'Drop out any food items connected to these dietary boundaries: {food_allergies_list_text}.'
    f'After selecting a recipe, guide the user with clear instructions of the cooking protocol.'
),
    verbose=True,
)

"""
For general understanding about crewai, I use one Agent() in this CrewAI task. With CrewAI, we can choose more than one Agent(). Each Agent has a different role,
goal, and backstory with different responsibilities. For example, we can choose 2 Agents such as culinary_agent, and dietary_agent.

 """

# I am defining 3 tasks with 1 agent. However, CrewAI gives opportunities to choose any number of tasks with 1 or more different agents.

from crewai import Task

# Task 1: Search recipe choices according to flavor_bases, and food_allergies

search_recipes_task  =  Task(
    description = ('Use the provided flavor parts, drop avoided allergens, and make at least three recipes with core components and a short explanation.'),

    expected_output = ' Provide a minimum of 3 recipes along with an overview of necessary ingredients.',

    agent = culinary_agent,
)

# Task 2: Take your best recipe.
select_best_recipe_task = Task(
    description = (
        'Overview all suggested recipes and then analyze them.'
        'Select a recipe that has test quality as well as dietary criteria.'
        'Give us some reasons behind your decision.'),

    expected_output = 'Final recipe as well as reasoning for your choice.',

    agent = culinary_agent,)

# Task # 3: Make an end-to-end recipe workflow
make_cooking_steps_task = Task(
    description = (
        'Put the selected recipe into an organized as well as clear explained cooking manual.'
        'Provide some details including cooking time, temperature limit, and helpful recommendations.'),

    expected_output = 'provide a completed cooking instructions in sequential order.',

    agent = culinary_agent,)



# State the Crew with a agent and tasks
# are tasks required in order? Left for research
# Define the Crew (group of agents + tasks working in sequence)

from crewai import Crew

kitchen_crew  = Crew(
    agents = [culinary_agent],
    tasks  =  [search_recipes_task, select_best_recipe_task, make_cooking_steps_task],
    planning = True,
    verbose = True,
)

# Run all tasks if they are in order.
outcomes_culinary_crew = kitchen_crew.kickoff()

# Like to see clean text

print(outcomes_culinary_crew.raw)



"""# using CrewAI for marketing research with multiple products"""

#%%capture
!pip install crewai-tools

# SerperDevTool acting as a tool to search real time internet data.

from crewai_tools import SerperDevTool

market_products_list =  [ 'protein snack', 'organic green tea']


marketing_experience = [
    'A goal focused marketing way supports on promoting healthy snacks as well as organic drinks with keeping brand name and holding customer participation.',
    'A marketing data analyst skilled in understanding consumer behavior, market competition, and campaigning strategies for healthy snacks, and organic beverages.',
    'A marketing expert showed for planning to launch products, research on market trends, and find target audiences for protein snack, organic green tea, and other healthy products.'
]

market_products_list_text = ','.join(market_products_list)
marketing_experience_text = ','.join(marketing_experience)

# Import necessary CrewAI classes

from crewai import Agent

# Agent # 1: Market Trends Specialist
Market_trends_specialist = Agent(
    role = 'Market Trends Specialist',

    goal = (f'Research on market patterns, understand buyer habits, and observe competitive approaches: {market_products_list_text}.'),

    backstory=('You have enough skills for market research as well asl market analysis.'
        ' Good experience for analyzing market signals and finding market growth possibilities.'),

    tools=[SerperDevTool()],
    verbose = True)

# Agent # 2: make some strategies based on market analysis

advisor = Agent(
    role = 'product improvement strategist',

    goal=(
        'Use market understanding to find results focused '
        f'marketing and Product identity approaches for these items: {market_products_list_text}.'),

    backstory=(
        f' You have solid experience in {marketing_experience_text}, so that your role is good for a brand strategist.'),
    verbose=True)

#  Task # 1: Run market analysis
collect_market_analysis_task  = Task(
    description=(
        f'Run online research to take key market patterns,'
        f'For {market_products_list_text}, it is demanding to focus for customer interest and market competition.'),

    expected_output = (
        'Report on current market patterns, and main competitors  including consumer preferences.'),
    agent = Market_trends_specialist)

# Task # 2: Generate market brand strategy plan

generate_market_brand_strategy_plan = Task(
    description=(
        f'make Brand identity alignment with best product using strategic approach involved in {market_products_list_text}.'
        'cover the focus group, and Key benefits with action plan.'
    ),

    expected_output = 'End to end marketing approach with covering target audience, and recommended actions  for market strategy.',

    agent = advisor,

    verbose = True
)



# link agents with tasks using Crew

crew_agents_tasks = Crew(

    agents = [Market_trends_specialist, advisor],

    tasks = [collect_market_analysis_task, generate_market_brand_strategy_plan],

    planning = True,

    verbose = True
)

from getpass import getpass

os.environ['SERPER_API_KEY'] = getpass('Super api key ')

print('super api key loaded and hided.')

# Run pipeline
crew_agents_tasks_results = crew_agents_tasks.kickoff()



print(crew_agents_tasks_results .raw)



"""#  Make your logical decisions with  a simple example using CrewAI’s flow pipeline"""

# I am interested in showing how CrewAI’s takes decision from my workflow engine

"""
My expectated outcome is win or lose or draw. This is the main goal of this project.
"""

import nest_asyncio

# Need to run all code lines without any error.
nest_asyncio.apply()


import random   #  expected:  random results such as draw, lose, and win

from crewai.flow.flow import Flow   # used for defining a workflow in crewai

from crewai.flow.flow import listen # Need to listen input data while flowing.

from crewai.flow.flow import router # Choose a path while the data flows.

from crewai.flow.flow import start # Help to initialize my project workflow (from here, my project starts).

from pydantic import BaseModel # input data flows a fixed data structure.



# State a data structure to hold the state of a match.
class MatchState(BaseModel):
  outcome: str = 'awaiting_result'  # expected results : 'draw', 'lose', 'win'



# state the match flow
class MatchFlow(Flow[MatchState]):

  @start()
  def start_match(self):
    print('the match start from here')

    # randomly select one of the three match results
    self.state.outcome = random.choice(['draw', 'lose', 'win'])
    print(f'Outcome: {self.state.outcome}')

  # flow starts from here.
  @router(start_match)
  def decide_route(self):
    # Choose the next step according to the state’s outcome.
    return self.state.outcome

  @listen('draw')
  def draw_outcome(self):
    print('final result is draw.')

  @listen('lose')
  def loss_notification(self):
    print('you lost match.')

  @listen('win')
  def win_notification(self):
    print('finalley, you got it.')


flow = MatchFlow()
flow.kickoff()



"""
# Final Thoughts:

•	CrewAI is used to make Agentic AI systems which can show decision autonomy with adaptive task coordination.
•	Successfully made multi-agent workflows pipeline.
•	LLM decision-making is integrated with applied AI systems within multi-agent control.
•	Project is usable for data science/data analytic/NLP/LLM/AI engineering.

"""

